### ISSUE TITLE
Does / Can cookies work with this ??

### ISSUE THREAD

**Issue by hayden-t** [mhgolkar/Weasel#4]
Thanks !

**Comment by mhgolkar** [comment]
I think you mean to send cookies (or headers in general) on connection request (?)

The *short answer is no*, because there is no standard/proper way to do that (with current design).
You can only pass URL (path) and protocols to construct a WS connection.
Please check out  [WebSocket] on MDN for detailed information.

BTW, I guess it is for authentication purposes.
Then you may try other ways to pass data to the server:

- **Depend on URL (or handshake)**:
In general, if you need to transfer data, (for authentication)  you can depend on URL parameters (for example `wss://server.tld/?token=xyz...`) or another handshake mechanism (e.g. by sending credentials as the first required message over the connection), depending on your server-side implementation.

- **Workaround (~ non-standard, probably unsafe in broader sense and not guaranteed to work)**:
If you really need to pass cookies and nothing else you may also try to work around this limitation by setting `document.cookie = 'token=xyz; SameSite=none; Secure';` (from your browser console) before creating a connection
but it **is not guaranteed to work**. Not at least with a lot of efforts. For example you should use `WSS` (secured connection) and the client (e.g. Weasel) shall be served (from server, not a local file), etc.

Hope you find this helpful.

[WebSocket]: https://developer.mozilla.org/en-US/docs/Web/API/WebSocket
